config/routes.rb
Learning::Application.routes.draw do

  get "sessions/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "new_post" => "posts#new", :as => "new_post"

  root :to => "home#index"
resources :users do
	resources :user_comments
end
resources :sessions

  resources :posts do
  	resources :comments

  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	SYNTAX=['Ruby','C++', 'Java', 'C', 'C#', 'CSS', 'HTML', 'Plain text']
	LISTING=['Listed', 'Unlisted']
	
  validates :name,  :presence => true

  validates :title, :presence => true,
                    :length => { :minimum => 5 }

  has_many :comments
	
end

app/models/user.rb
class User < ActiveRecord::Base
    include Gravtastic
    has_many :user_comments
gravtastic :fieldname
  
  attr_accessible :email, :password, :password_confirmation, :bio, :fieldname
    validates :email,  :presence => true
    validates :bio, :presence => true
    validates :fieldname, :presence => true
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  

end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

private



def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create 
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment])
		redirect_to post_path(@post)
		
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
  
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
end

def create
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_url
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url
end

end

app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController
 def create
    @user = User.find(params[:user_id])
    @user_comments = @user.user_comments.create(params[:user_comment])
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
   def index
    @user = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @user }
    end
  end
  
def new
  @user = User.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @user }
      end
end

  def edit
    @user = User.find(params[:id])
  end
  
    def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'Profile was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

def create
  @user = User.new(params[:user])
          
  if @user.save
    redirect_to root_url
 
  else
   render :action => "new" 
end
end
def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def facebook_like
            content_tag :iframe, nil, :src => "http://www.facebook.com/plugins/like.php?href=#{CGI::escape(request.url)}&layout=standard&show_faces=true&width=480&action=like&font=arial&colorscheme=light&height=10", :scrolling => 'no', :frameborder => '0', :allowtransparency => true, :id => :facebook_like
          end
        
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<style type = "text/css">
div.content
{
border-radius:15px;
width:500px;
padding:10px;

background-color:#bababa;
margin:0px;
}
div.subcontent
{
border-radius:15px;
width:300px;
padding:10px;

background-color:#959595;
margin:0px;
}
</style>
<div align=center>

</div>
<div align=center>



</div>

<% if current_user %>
  	<table>
  <tr>
    
    
  </tr>

<b><h1>Your Dashboard:</h1></b>

	<div class = "content">
	<h3> You're logged in as <%=current_user.email%> </h3>
	<%= image_tag current_user.gravatar_url %> 
	<div class = "subcontent">
	<%=simple_format(current_user.bio )%>
	<a href="/users/<%=current_user.id%>/edit">Edit Your Profile!</a>
	
	</div>
	
	</div>

	
  	<% else %>
   <img src = "/images/homepage.png">
  <% end %>

<div align=center>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

<head>
<style type="text/css">
h3{font-family: 'Oxygen', sans-serif;}

</style>
<img src="/images/seperator.png">
  <title>CodeShare - CodePasting Tool</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
<link rel="stylesheet" type="text/css" href="/stylesheets/main.css" />
</style>

<script type="text/javascript">
function placeIt() {
if (!document.all) {
document.getElementById("top_bar").style.top = window.pageYOffset +"px"; // For Mozilla etc.
document.getElementById("loginbox").style.top = window.pageYOffset +"px"; // For Mozilla etc.
} else {
document.getElementById("top_bar").style.top = document.documentElement.scrollTop +"px"; // For the IE...
document.getElementById("loginbox").style.top = document.documentElement.scrollTop +"px"; // For the IE...
}

}
</script>
  
</div>
</div>
</head>



<body onload="placeIt()">

	
	<div id="top_bar">
	
  <div align=center>
  


<%= link_to image_tag("/images/head.png", :border => 
0 ), root_path , :title => "Home Page" %> 
<h3>
  <% if current_user %>
  	<%= link_to 'All Codes', posts_path %>  --
  	
    Logged in as <%= link_to current_user.email, current_user %>--
    <%= link_to 'New Code', new_post_path %> --
    <%= link_to "Log out", log_out_path %> 
    
  	<% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
	  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

	</h3>
	


</div>
<!-- LOGIN AND SIGN UP BUTTONS -->
<!--
<a href="http://184.167.244.157:3000/sign_up"><img src="/images/buttons/minibutton_register.png"></a>
<a href="http://184.167.244.157:3000/log_in"><img src="/images/buttons/minibutton_login.png"></a>
-->
</div>

<div align=center>
	<div id="user_nav">
 
  <%= yield %>
</div>
</div>

</body>

<footer onLoad="placeIt()">


<div align=center>

    <h6>Made with love (<3) by <a href="http://twitter.com/thatredant">@ThatRedAnt, </a>
 <a href="http://twitter.com/des_alex">@Des_alex, </a>  & 
          <a href="http://twitter.com/squintyeyed">@SquintyEyed. </a></h6>
  </div>
  <br>
</footer>
</html>

app/views/posts/_form.html.erb
<style type="text/css">
div.content
{
width:500px;
padding:10px;
border-radius: 15px;
background-color:#bababa;
margin:0px;
}

div.subcontent
{
width:300px;
padding:10px;
border-radius: 15px;
background-color:#868686;
margin:0px;
}
div.name
{
opacity:0;
}
</style>

<%= form_for(@post) do |f| %>
 	  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <br>
  <div class="field">
    <div class="content">
    <h2><%= f.label :title %></h2>
    <%= f.text_field :title %>
  </div>
  </div>
  <br>
  <div class="field">
    <div class="content">
    <h2><%= f.label :content %></h2>
    <%= f.text_area :content %>
  </div>
  </div>
  <br>

   <div class="field">
     <div class="content">
  <h2><%= f.label :syntax %></h2>

  <%= f.select( :syntax, Post::SYNTAX) %>
</div>
 </div>
 <br>
 <div class="field">
     <div class="content">
  <h2><%= f.label :listing %></h2>

  <%= f.select( :listing, Post::LISTING) %>
</div>
 </div>
 <br>

  <div class="actions">
    <%= f.submit %>
  </div>
  
  <div class="name">

      <h2><b><%= f.label :Creator %></b></h2>


		    <%@post.name  = current_user.email%> 
        <%= f.text_field :name  , :readonly => true %>

  </div>
  
<% end %>

app/views/posts/all.html.erb
<html>
<head>
<style type="text/css">
table, td, th
{
border:1px solid gray;
}
th
{
background-color:gray;
color:white;
}
</style>
</head>
</html>
<title>Community Blog</title>
<div align=center>
<h1>Listing posts</h1>
</div>
<div align=center>
<table>
  <tr>
    <th><p>Name</p></th>
    <th><p>Title</p></th>
    <th><p>Content</p></th>
    <th><p>Location</p></th>
    <th>
    <th>
    <th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= post.location %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Delete', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>
<br />
<div align=center>
<%= link_to 'New Post', new_post_path %>
</div>
<div align=center>
<p>
Logo by Alex B.(@Des_alex)
</p>
</div>

app/views/posts/index.html.erb
<html>
<head>
<style type="text/css">
div.post
{
border-radius: 15px;
width:500px;
padding:10px;
border: 2px;
background-color:#bababa;
margin:0px;
}

div.postcontent
{
border-radius: 15px;
width:300px;
padding:10px;

background-color:#868686;
margin:0px;
}

table, td, th
{
border:1px solid gray;
}
th
{
background-color:gray;
color:white;
}
</style>
</head>
</html>
<% if current_user %>
<div align=center>

<h1>All Codes</h1>

</div>




<% @posts.each do |post| %>
<% if post.listing == 'Listed' %>
	<div class = "post">
    <p><b><%= post.title %></b>, by <b><%=post.name%></b> </p> 
    <div class = "postcontent">
    <p><b><%= post.content %></b></p>
    </div>
    <br>
  	<%= link_to 'Show Full', post %>
    
    </post>
      
    </div>
    </div>
<br>



<%end%>


	


<% end %>



</div>

<% else %>
<h1>You must be logged in to access this page.</h1>
<%end%>
<div align=center>

</div>

<div align=center>

</div>

app/views/posts/new.html.erb
<html>
<title>Community Blog</title>
<div align=center>
<% if current_user %>
<h1>New Code</h1>
</div>
</html>
<div align=center>
<%= render 'form' %>
</div>
<% else %>
<h1>Sorry, you must be logged in to create a new post!</h1> 
<%end%>
<div align=center>
<%= link_to 'Back', posts_path %>
</div>
<html>
<div align=center>

</div>
</html>

app/views/posts/show.html.erb
<html>
<link href='http://fonts.googleapis.com/css?family=Norican' rel='stylesheet' type='text/css'>

<style type="text/css">
div.content
{
width:500px;
padding:10px;
border-radius: 15px;
background-color:#bababa;
margin:0px;
}

div.subcontent
{
width:300px;
padding:10px;
border-radius: 15px;
background-color:#868686;
margin:0px;
}

div.page
{
width:800px;
padding:10px;
border:5px solid gray;
background-color:#bababa;
margin:0px;
}

div.box
{
width:600px;
padding:10px;
border:5px solid gray;
background-color:#959595;
margin:0px;
}
</style>
<% if current_user.email == "CodeShare"%>
<td><%= link_to 'Delete', @post, :confirm => 'Are you sure?', :method => :delete %></td>
<%end%>
  </tr>
<div align=center>

<p id="notice"><%= notice %></p>



<p>
  
  <h1><%= @post.title %> </h1>
  
</p>

<p><div class="content">
  <h4><b>Creator:</b></h4>
  <div class="subcontent"><%= @post.name %> </div></div>
</p><div class="content">
<h4><b>Syntax:</b></h4>
  <div class="subcontent"><%=simple_format(@post.syntax )%></div></div>
<p><div class="content">
  <h4><b>Content:</b></h4>

    <div class="subcontent"><div align = left><pre><%=@post.content%></pre></div></div></div>
</p>

<%=facebook_like%>
</div>

</html>

app/views/users/edit.html.erb
<style type = "text/css">
div.content
{
width:500px;
padding:10px;
border-radius: 15px;
background-color:#bababa;
margin:0px;
}

div.subcontent
{
width:300px;
padding:10px;
border-radius: 15px;
background-color:#868686;
margin:0px;
}
</style>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if current_user %>
  <% if current_user.email == @user.email%>
<h1>Edit your profile!</h1>
	<br>
<div class="content">
		<%=@user.email%>
    </div>
    </div>
    <br>
	<div class="content">
	  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
    </div>
    </div>
    <br>
    	<div class="content">
	  <div class="field">
    <%= f.label :email%><br />
    <%= f.text_field :fieldname %>
    </div>
    </div>
    <br>
  <p class="button"><%= f.submit %></p>
  

  	<%else%>
  
  	<h1> You do not have access to this page! </h1>
  	


<% end %>



<%else%>
  
  	<h1> You do not have access to this page! </h1>
  	
<% end %>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up! :)</h1>
<br>
<style type = "text/css">
div.content
{
width:500px;
padding:10px;
border-radius: 15px;
background-color:#bababa;
margin:0px;
}

div.subcontent
{
width:300px;
padding:10px;
border-radius: 15px;
background-color:#868686;
margin:0px;
}
</style>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  	<div class="content">
	  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :email %>
    </div>
    </div>
    <br>
    <div class="content">
    <div class="field">
    <%= f.label :email %> <p> (This is only used for your gravatar. <a href = "http://gravatar.com/" > What's that? </a>)<br />
    <%= f.text_field :fieldname %>
    </div>
    </div>
    <br>
        <div class="content">
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_field :bio %>
    </div>
	</div>
	<br>
    <div class="content">
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
    </div>
	</div>
	<br>
	<div class="content">
  	  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  </div>
  <br>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<html>

<% if current_user.email == "CodeShare"%>
<td><%= link_to 'Delete', @user, :confirm => 'Are you sure?', :method => :delete %></td>
<%end%>
<style type="text/css">div.content
{
background-color:#bababa;
width:220px;
padding:10px;
border-radius:15px;
margin:0px;
}
div.subcontent{
background-color:#868686;
width:200px;
padding:10px;
border-radius:15px;
margin:0px;
}
div.bio{

background-color:#bababa;
width:300px;
padding:10px;
border-radius:15px;
margin:0px;
}
</style>
<div class="row-fluid">
  <div class="span12">
   <div align=center>

<p id="notice"><%= notice %></p>

<p>

  <tr>
  <div class = "content">
  	
    <td><b><h3><%=@user.email %>'s Profile. </h3><%= image_tag @user.gravatar_url %></b></td>
	

    


</div>









</p>
    <div class="row-fluid">
    
      <div align="center"> <div class = "bio"><b>Bio:</b><p><div class="subcontent"> <%=simple_format( @user.bio )%></p></div></div></div>


    </div>
  
</div>





</div>
  

</html>